apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: pod
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  containers:
  - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
    name: {{ .Values.image.repository }}
    ports:
    - containerPort: {{ .Values.port.number }}
      protocol: {{ .Values.port.protocol }}
      name: {{ .Values.port.name }}

