apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
    name: nginx
    ports:
    - containerPort: 8080
      protocol: TCP
      name: http

