apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
  - name: init
    image: busybox
    command:
    - sh
    - -c
    - 'date; sleep 10'
  containers:
  - image: busybox
    name: main
    command:
    - sh
    - -c
    - 'date; echo "Main container started"; sleep 10000'

