apiVersion: v1
kind: Pod
metadata:
  annotations:
    team: development
  labels:
    run: nginx-pod
  name: nginx-pod
spec:
  nodeSelector:
    az: az1
  containers:
  - image: nginx
    name: nginx
